name: Unit Test

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install NetworkX
              run: pip install networkx
            - name: Install NumPy
              run: pip install numpy
            - name: Install testing dependencies
              run: pip install pytest pytest-cov mypy coveralls
            - name: Install lcov
              run: sudo apt-get install -y lcov
            - name: Run unit tests with coverage
              run: make coverage
            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                path-to-lcov: ./coverage/lcov.info
                github-token: ${{ secrets.GITHUB_TOKEN }}
